services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=damn'
      - 'POSTGRES_PASSWORD=aboba'
      - 'POSTGRES_USER=aboba'
    volumes:
      - ./docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./src/main/resources/db/data:/var/lib/postgresql
    ports:
      - "5432:5432"