services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=damn'
      - 'POSTGRES_PASSWORD=aboba'
      - 'POSTGRES_USER=aboba'
    volumes:
      - ./docker-entrypoint-init.d/init.sql:/docker-entrypoint-init.d/init.sql
      - postgresql_data:/var/lib/postgresql/data/
    ports:
      - '5432'

volumes:
  postgresql_data:
    driver_opts:
      device: "${PWD}/test"
      type: none
      o: bind